### PR TITLE
Added option for always open Maps (without close button) and for rela…

### PR DESCRIPTION
**Pull request by paulwuertz**
Added option for always open Maps (without close button) and for relative fixed container for the map to appear in.
Just see the example.html, which has both features showing in one example. I needed it for a form in another project. I think the options make most sense combined, but ya, who knows. Would be glad about some feedback, because I am definitly far far from a modern JS dev, normally I am an embedded guy ^^

### CODE REVIEW

**Comment by stefanocudini** [comment]
hi @paulwuertz This branch has conflicts that must be resolved

**Comment by paulwuertz** [comment]
I rebased on your master :)

**Comment by stefanocudini** [comment]
hi tnkyou @paulwuertz  what is new option mapContainer?

**Comment by paulwuertz** [comment]
When you want to have a fixed container on your site to display the map in you need to specify an element selector for which element will be the container...
Probably I should have described it in the simple.html example with one phrase.
Hope you like the feature :) 
I find it was nice for fine tuning and visual feedback in some situations.

**Comment by stefanocudini** [comment]
updated version 0.3.2 on npm:
https://www.npmjs.com/package/leaflet-locationpicker

**Pull request merged**
