### PR TITLE
Few more tweaks

### PR DESCRIPTION
**Pull request by jkufner**
Hello, here is another batch of little changes :)

Tile URL is now set to HTTP or HTTPS depending on what is used on page. Close button uses the same markup & style as zoom buttons. Picker moves when window is resized. And some cleanup.

### CODE REVIEW

**Comment by stefanocudini** [comment]
hi @jkufner what is your npm account?  I want add you in collaborators list for this plugin!
https://www.npmjs.com/package/leaflet-locationpicker

**Comment by jkufner** [comment]
Here: https://www.npmjs.com/~jkufner

**Comment by stefanocudini** [comment]
done!

my raccomandation is update sometimes the git tags in incremental way

**Comment by jkufner** [comment]
Thanks :)

**Comment by stefanocudini** [comment]
thanks to you for contributions

**Pull request merged**
